### ISSUE TITLE
some errors in current code

### ISSUE THREAD

**Issue by jdmontenegro** [AntonBankevich/mosaic#1]
Dear Anton,

Hope you are well. I am trying the current mosaic code to solve a pretty complex region that Flye alone has not been able to solve correctly. However I can see a few errors when testing it with the toyset. BTW, I am running on a 24 core, 256GB RAM server with Centos 7.0.

1) GLIBC_2.27
The default GLIBC version for Centos 7.0 is 2.17. I am asking the system admin to upgrade it to 2.27, but it appears to be more troublesome than iniatially tought. Is there any way it can be made compatible wit older GLIBC versions, or at least if it could be compilable from source?
```
$ ./mosaic --reads test_dataset/reads.fasta -o tmp --contigs test_dataset/axbctbdy.fasta
20.07.28 00:37:39  INFO: Command line: ./mosaic --reads test_dataset/reads.fasta -o tmp --contigs test_dataset/axbctbdy.fasta
20.07.28 00:37:39  INFO: Started
20.07.28 00:37:39  INFO: Preparing initial state
20.07.28 00:37:39  INFO: Creating read collection
/home/Bioinformatics/tools/mosaic/bin/flye-modules: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/Bioinformatics/tools/mosaic/bin/flye-modules)
Traceback (most recent call last):
  File "./mosaic", line 26, in <module>
    mosaic_main.assemble(sys.argv, bin_path)
  File "/home/Bioinformatics/tools/mosaic/py/disjointig_resolve/mosaic_main.py", line 99, in assemble
    disjointigs_file = constructDisjointigs(reads, params.expected_size, assembly_dir)
  File "/home/Bioinformatics/tools/mosaic/py/disjointig_resolve/initialization.py", line 316, in constructDisjointigs
    "--config", "flye/config/bin_cfg/asm_raw_reads.cfg", "--min-ovlp", "1500", "--threads", str(params.threads), "--log", log_file])
  File "/home/Bioinformatics/tools/SMRTLink/smrtlink/install/smrtlink-release_8.0.0.80529/bundles/smrttools/install/smrttools-release_8.0.0.80502/private/thirdparty/python/python_2.7.16/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/Bioinformatics/tools/mosaic/bin/flye-modules', 'assemble', '--reads', 'tmp/assembly_initial/reads.fasta', '--out-asm', 'tmp/assembly_initial/disjointigs.fasta', '--genome-size', '5000000', '--config', 'flye/config/bin_cfg/asm_raw_reads.cfg', '--min-ovlp', '1500', '--threads', '16', '--log', 'tmp/assembly_initial/log.txt']' returned non-zero exit status 1
```
2) some options not recognized
The current help gives several running options:
`usage: mosaic --reads <file> -o <dir> (--genome-size <int> | --flye-dir <dir> | --contigs <contigs>) [--threads <int>]`
However, neither "--genome-size" nor "--threads" are currently available and throw an error:
```
option --genome_size not recognized
option --threads not recognized
```
Do you have any other recommended way of testing the current version. If you could give me some advice on how best to test it, I would be grateful.

Kind regards,

Juan D. Montenegro

**Comment by AntonBankevich** [comment]
Dear Juan,
Thank you for your interest in mosaicFlye. Unfortunately the release was a bit hurried and as the results it contains some problems. I am preparing new release but it won't be ready for several weeks. So for now I can suggest some quick fixes.
1. As I understand you have Flye installed on your server. The binaries that are in mosaicFlye release are Flye2.7 binaries. Thus if you have working Flye binaries you could just copy contents of bin directory of Flye to bin directory of mosaicFlye. If this does not help or if it is impossible for some reason, let me know and I can prepare a small release with binaries that should work for you.
2. That's embarrassing but I forgot to add --threads parameter. You can use -t instead. As for genome size it should be --genome-size instead of --genome_size (- instead of _).

**Comment by gitcruz** [comment]
Hi Anton,
What I find a bit weird is that I need to use python2 to execute mosaic (e.g. PYTHON/2.7.6) and python3 to run flye (e.g. PYTHON/3.7.1). I am testing it on a cluster so I normally load either PYTHON2 or 3 before using a program. I cannot use both at the same time. For Flye version2.6  I am using PYTHON/3.7.1. Is this normal? Perhaps I am missing some python basics here... Thanks, F.
